{% set name = "rpcompletion" %}
{% set version = "6.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rpCompletion/archive/refs/tags/{{ version }}.tar.gz
  sha256: e263b18a0d5f27a2a4cec664e3eb5be4c0206f418dc303033d1f0f893876e966

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - rdkit
    - rr_cache >=3.6.3
    - brs_utils >=1.26.0
    - rxn_rebuild >=3.1.7
    - rplibs >=6.9.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - rpcompletion

about:
  home: https://github.com/brsynth/rpCompletion/tree/main
  summary: "Completes mono-component reactions output by RetroPath2.0 with the appropriate cofactors."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
    - breakthewall
    - tduigou
